d((d_opr.id == 44 & d_opr.trial == 4) |...
            (d_opr.id == 43 & d_opr.trial== 20) |...
            (d_opr.id == 43 & d_opr.trial== 7) |...
            (d_opr.id == 9 & d_opr.trial==20 ) |...
            (d_opr.id == 8 & d_opr.trial== 20),:) = [];
